version: '3.1'
services:
  timesketch:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    container_name: timesketch
    ports:
      - "80:80"
    links:
      - elasticsearch
      - postgres
      - redis
    environment:
      - POSTGRES_USER=timesketch
      - POSTGRES_PASSWORD=password
      - POSTGRES_ADDRESS=postgres
      - POSTGRES_PORT=5432
      - ELASTIC_ADDRESS=elasticsearch
      - ELASTIC_PORT=9200
      - REDIS_ADDRESS=redis
      - REDIS_PORT=6379
      - NEO4J_ADDRESS=neo4j
      - NEO4J_PORT=7474
      - TIMESKETCH_USER=timesketch
      - TIMESKETCH_PASSWORD=password
    restart: always

  elasticsearch:
    environment:
      - ES_JAVA_OPTS= -Xms1g -Xmx1g # 1G min/1G max
    image: elasticsearch
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    restart: always
    volumes:
      - ../contrib/:/usr/share/elasticsearch/config/scripts/
      - /var/lib/elasticsearch:/usr/share/elasticsearch/data/elasticsearch

  postgres:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=timesketch
      - POSTGRES_PASSWORD=password
    restart: always
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data


  redis:
    image: redis
    container_name: redis
    volumes:
      - /var/lib/redis:/data

  neo4j:
    image: neo4j
    container_name: neo4j
    environment:
      - NEO4J_AUTH=none
    restart: always
    volumes:
      - /var/lib/neo4j/data:/var/lib/neo4j/data
